vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /assets/img/plateformes
            upload_destination: '%kernel.project_dir%/public/assets/img/plateformes'
            namer: Vich\UploaderBundle\Naming\UniqidNamer        
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
