course_show:
  path:
    fr: /cours/{id}
    ar: /courses/{id}
  controller: App\Controller\CourseController::show

course_index:
  path:
    fr: /cours/{name}
    ar: /courses/{name}
  controller: App\Controller\CourseController::index
