index:
  path:
    fr: /
    ar: /ar
  controller: App\Controller\DefaultController::index

section_level:
  path:
    fr: /{name}
    ar: /ar/{name}
  controller: App\Controller\DefaultController::sectionLevel
