index:
  path:
    fr: /
    ar: /ar
  controller: App\Controller\DefaultController::index

section:
  path:
    fr: /{level}
    ar: /ar/{level}
  controller: App\Controller\DefaultController::section
